[general]
operator_wots_pubkey_file = "data/public/wots_pub.json"
vkey_file = "data/public/groth16/vkey.bin"
proof_file = "data/public/groth16/proof.bin"
pubin_file = "data/public/groth16/pubin.bin"
partial_scripts_file = "data/public/partial_scripts.json"
disprove_scripts_file = "data/public/disprove_scripts.json"
signed_assertions_file = "data/public/signed_assertions.json"

[operator]
operator_wots_seckey_file = "data/private/wots_sec.json"